#! /usr/bin/env bash

# Examples
# deploy banana

env="${1:-banana}"
pr="$(git branch --show-current)"

git branch "${env}" --force
git checkout "${env}"

git rev-parse HEAD >> sha
git add sha
git commit -m "Tag with sha"

git push origin "${env}" --force
gh workflow run deploy_to_dev.yaml \
    --field environment=development-"${env}" \
    --ref="${env}"

git checkout $pr
