#! /bin/bash

apt-get update &&
apt-get install -y libcurl4-openssl-dev libssl-dev libssh2-1-dev libxml2-dev

echo 'options(repos = c(CRAN = "https://packagemanager.rstudio.com/all/__linux__/bionic/latest"))' > ~/.Rprofile

Rscript -e 'install.packages("tidyverse")'
Rscript -e 'install.packages(c("devtools", "testthat", "roxygen2"))'
Rscript -e 'install.packages("remotes")'
Rscript -e 'remotes::install_local(".", dependencies = TRUE)'
