#! /bin/bash

docker run \
    -d \
    --name verse \
    -v /mnt:/mnt \
    -v "$(pwd)":"/home/rstudio" \
    -p 8787:8787 \
    -e ROOT=true -e DISSABLE_AUTH=true -e PASSWORD=123 \
    rocker/verse

