#! /bin/bash

for i in $(cat editors)
do
  gh issue list --limit 1 -S "assignee:$i state:open state:closed sort:updated" \
    --repo ropensci/software-review \
    --json number,state,updatedAt,assignees --template \
    '{{range .}}{{tablerow .state (pluck "login" .assignees | join ",") (printf "#%v" .number)  (timeago .updatedAt) }}{{end}}' | cat  
done
