#!/usr/bin/env bash

# # Examples:
#
# editors_last_activity
# 
# # Pretty
# editors_last_activity >> tempfile | column -t | sort
for i in $(cat editors)
do
  gh issue list --limit 1 -S "assignee:$i state:open state:closed sort:updated" \
    --repo ropensci/software-review \
    --json number,state,updatedAt,assignees --template \
    '{{range .}}{{tablerow .updatedAt (printf "#%v" .number) .state  (pluck "login" .assignees | join ",") (timeago .updatedAt)}}{{end}}' | cat  
done
