#!/bin/bash

Rscript -e 'recast.geolift::run_app()' 2>&1 | while IFS= read -r line; do
  echo "$line"
  url=$(echo "$line" | sed -n 's/.*Listening on \(http[^ ]*\).*/\1/p')
  if [[ -n "$url" ]]; then
    open -a "Google Chrome" "$url"
  fi
done
