#!/usr/bin/env bash

# Show aliases for CRAN release
#
# Examples
# # Show all
# alias-release
#
# Show matching "remote"
# alias-release remote
MY_ALIASES="/home/mauro/git/dotfiles/aliases.zsh" 
cat "$MY_ALIASES" | grep ${1:-""}
