#!/usr/bin/env bash

# Show aliases for CRAN release
#
# Examples
# # Show all
# alias-release
#
# Show matching "remote"
# alias-release remote
myaliases-verbose ${1:-""} \
  | cut -d" " -f 2 | cut -d"=" -f 1

