#! /bin/bash

# Apply commands to each directory detected by pacta-locate

here=$(pwd)
for repo in $(pacta-locate)
do
    echo "$(basename ${repo}):"
    # Work here -------------------------------------------
    cd $repo
    # git status -s
    # -----------------------------------------------------
    echo --
    echo
done
cd $here
exit 0
