#! /bin/bash

# Find subdirectories with an empty file named '.pacta' at their root.

# $1 Path where to start the search, i.e. the parent of the sibling
# subdirectories you want to find.

at="${1:-$(pwd)}"
out="$(find ${at} -maxdepth 2 -empty -type f -name '.pacta')"

if [ -z "$out" ]
then
    exit 0
else
    echo "$out" | sort | xargs dirname
fi

exit 0
