#! /bin/bash

# Apply commands in a sigle-quoted string over each pacta repo
# by evaluating $i (each pacta repo).

# $1: A single-quoted string starting usually
# including each repo's pronoun $i -- e.g. 'eval echo $i'.

# Examples:
# pacta-eval-i 'eval git -C $i status'
# pacta-eval-i 'eval git -C $i log --oneline --decorate | head -1'

here=$(pwd)

commands='eval '$1
for i in $(pacta-find)
do
    echo "* $(basename $i):"
    $commands
    echo
    echo
done

cd $here
