#! /bin/bash

restore_directory=$(pwd)
restore_branch=$(git rev-parse --abbrev-ref HEAD)

function pull_origin_master {
    cd ../"$1"
    echo "$(basename $(pwd))"
    git checkout master
    git pull origin master
    echo "."
    echo "."
}

for repo in $(pacta-repos)
do
    pull_origin_master $repo
done

cd "$restore_directory"
git checkout "$restore_branch"
