#! /bin/bash

# Find subdirectories with an empty file named '.pacta' at their root.

out="$(find $(pwd) -maxdepth 2 -empty -type f -name '.pacta')"

if [ -z "$out" ]
then
    exit 0
else
    echo "$out" | sort | xargs dirname
fi

exit 0
