#! /bin/bash

current_branch=$(git rev-parse --abbrev-ref HEAD)

cd ../PACTA_analysis
echo PACTA_analysis
git rev-list master -1

cd ../create_interactive_report
echo create_interactive_report
git rev-list master -1

cd ../pacta-data
echo pacta-data
git rev-list master -1

cd ../StressTestingModelDev
echo StressTestingModelDev
git rev-list master -1

git checkout "$current_branch"
