#! /bin/bash


here="$(pwd)"

# Defaults:
into="pacta"
parent="$(pwd)"
locally=0
url="git@github.com:2DegreesInvesting/"
tag="latest"

for arg in "$@"
do
    case $arg in
        --parent)
        parent="$2"
        shift
        shift
        ;;
        --into)
        into="$2"
        shift
        shift
        ;;
        --locally)
        locally=1
        shift
        ;;
        --url)
        url="$2"
        shift
        shift
        ;;
        --tag)
        tag="$2"
        shift
        shift
        ;;
    esac
done

cd $parent
local_repos="$(pacta-find)"

echo "Cloning siblings into: $into"
cd $into || exit 1
echo

if [  $locally == 1 ]
then
   for repo in $local_repos
    do
        git clone -b master --local $repo || exit 1
        echo
    done
else
    for repo in $local_repos
    do
        remote="${url}$(basename ${repo}).git"
        git clone -b master $remote --depth 1 || exit 1
        echo
    done
fi

# TODO:
cd $here
exit 0

for repo in ${clones}
do
    echo "${repo} HEAD sha:"
    git -C "${repo}" rev-parse HEAD
    echo "--"
done

for repo in ${clones}
do
    git -C "${repo}" tag -a "${tag}" -m "Release pacta ${tag}" HEAD
    echo "${repo}"
    echo "$(git -C ${repo} log --pretty='%h %d <%an> (%cr)' | head -n 1)"
    echo "--"
done

docker rmi --force $(docker images -q '2dii_pacta' | uniq)
docker build --tag 2dii_pacta:"${tag}" --tag 2dii_pacta:latest .

for repo in ${clones}
do
    rm -rf "${repo}"
done

unzip pacta_web_template.zip

git clone -b master "${url}"user_results.git --depth 1
echo "user_results HEAD sha:"
git -C user_results rev-parse HEAD

needless_files=".git .gitignore .DS_Store README.md user_results.Rproj"
for file in ${needless_files}
do
  rm -rf user_results/"${file}"
done

cp -R user_results/ pacta_web/user_results/4/
rm -rf user_results

docker save 2dii_pacta | gzip > pacta_web/2dii_pacta.tar.gz

zip -r pacta_web.zip pacta_web -x ".DS_Store" -x "__MACOSX"

rm -rf pacta_web

exit 0
