#! /bin/bash

# $1: Optional path to a pacta sibling or its parent.

# Examples
# pacta-sync
# pacta-sync ~/git/pacta-data

for repo in $(pacta-find ${1:-$(pwd)})
do
    repos+="$(basename $repo)"
done

echo $repos
exit 0
restore_directory=$(pwd)
restore_branch=$(git rev-parse --abbrev-ref HEAD)

function pull_origin_master {
    cd ../"$1"
    echo "$(basename $(pwd))"
    git checkout master
    git pull origin master
    echo "."
    echo "."
}

for repo in $(basename $(pacta-find))
do
    pull_origin_master $repo
done

cd "$restore_directory"
git checkout "$restore_branch"
