#! /bin/bash

# $1: Optional path to a pacta sibling or its parent.

# Examples
# pacta-sync
# pacta-sync ~/git/pacta-data

here=$(pwd)
branch="$(git rev-parse --abbrev-ref HEAD 2>/dev/null)"

path="${1:-$(pwd)}"
repos="$(pacta-find $path)"
for repo in $repos
do
    cd "$repo"
    echo "$(basename $repo)"
    git checkout master
    git pull origin master
    echo
    git log  --pretty='%h % %s (%cr) <%an>' | head -1

    
    echo

done

cd "$here"
git checkout "$branch" 2>/dev/null
