#! /bin/bash

# $1: Optional path to a pacta sibling or its parent.

# Examples
# pacta-sync
# pacta-sync ~/git/pacta-data

restore_directory=$(pwd)
restore_branch="$(git rev-parse --abbrev-ref HEAD 2>/dev/null)"

path="${1:-$(pwd)}"
repos="$(pacta-find $path)"
for repo in $repos
do
    cd "$repo"
    echo "$(basename $repo)"
    git checkout master
    git pull origin master
    echo
done

cd "$restore_directory"
git checkout "$restore_branch" 2>/dev/null
